name: Deploy Terraform

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy"
        type: choice
        options: [dev, test, prod]
        default: dev

env:
  environment: ${{inputs.environment}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: terraform
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOYMENT_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - run: |
          terraform init \
            -backend-config="bucket=${{ vars.TF_S3_BACKEND_BUCKET_NAME }}" \
            -backend-config="key=state/github-oidc/${{ inputs.environment }}/terraform.tfstate" \
            -backend-config="region=${{ vars.AWS_REGION }}"

      - run: terraform validate

      - run: terraform plan -var-file="env/${{ inputs.environment }}.tfvars" -var="aws_region=${{ vars.AWS_REGION }}" -out=tfplan

      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: ${{ github.actor }}
          minimum-approvals: 1
          issue-title: "Deploying to ${{ inputs.environment }} environment"
          issue-body: "Please review the Terraform plan and approve this deployment to ${{ inputs.environment }}."

      - run: terraform apply tfplan
